# Set update schedule for GitHub Actions

version: 2
on:
  workflow_dispatch:
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: "daily"
